/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgarchilin
 */
public class PoliceDB extends javax.swing.JFrame {

    public Object[] ob;
    private int row;

    /**
     * Creates new form PoliceDB
     */
    public PoliceDB() {
        initComponents();
        try {
            //  SQLConnections.getConnection();
            // SQLConnections.RetrieveInformaiton();
            Refresh();
        } catch (Exception ex) {
            Logger.getLogger(PoliceDB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Refresh() {
        SQLConnections.OfficerInformation();
        SQLConnections.OfficerAssigments();
        SQLConnections.callerInformaiton();
        SQLConnections.AlarmInformation();
        SQLConnections.IncidentReportInfo();
        OfficerAssignmentTableUpdate();
        OfficerTable();
        updateIncidentReport();
        CallerTable();
        AlarmTableGrid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JTabbedPane();
        MakeCall = new javax.swing.JPanel();
        MakeCallName = new javax.swing.JTextField();
        MakeCallDescritpion = new javax.swing.JTextField();
        SubmitCall = new javax.swing.JToggleButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Alarm = new javax.swing.JTable();
        AlarmNumberVerify = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        AlarmWindow = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        OperatorFinalPage = new javax.swing.JPanel();
        Description = new javax.swing.JTextField();
        CallerName = new javax.swing.JTextField();
        PoliceCode = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        GetCall = new javax.swing.JButton();
        SendReport = new javax.swing.JButton();
        Location = new javax.swing.JTextField();
        IncidentType = new javax.swing.JTextField();
        Priority = new javax.swing.JTextField();
        Operator = new javax.swing.JPanel();
        callNumberText = new javax.swing.JTextField();
        CallerIDsave = new javax.swing.JTextField();
        Addop = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Dispatcher = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        ReportSearch = new javax.swing.JTextField();
        GetReport = new javax.swing.JButton();
        IncidentNameDP = new javax.swing.JTextField();
        IncidentNumberDP = new javax.swing.JTextField();
        StartAssigning = new javax.swing.JButton();
        newDispatcher = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        DispatcherLocation = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        ClearDp = new javax.swing.JButton();
        Officer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        SearchButton = new javax.swing.JTextField();
        SearchLocation = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        FinalAssignment = new javax.swing.JTextField();
        CompleteAssignment = new javax.swing.JButton();
        FinalIncidentNumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        EditStatus = new javax.swing.JTextField();
        UpdateBadgeStatus = new javax.swing.JTextField();
        UpdateStaus = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Complete = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AssigmentStatusTable = new javax.swing.JTable();
        AssignmentPK = new javax.swing.JTextField();
        CompleteUpdate = new javax.swing.JButton();
        Verify = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Refresh = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Home.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Home.setMaximumSize(new java.awt.Dimension(500, 500));
        Home.setPreferredSize(new java.awt.Dimension(747, 590));
        Home.setRequestFocusEnabled(false);

        MakeCallName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeCallNameActionPerformed(evt);
            }
        });

        SubmitCall.setText("Make Call");
        SubmitCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitCallActionPerformed(evt);
            }
        });

        Alarm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alarm Number", "Name", "Type", "Location"
            }
        ));
        jScrollPane5.setViewportView(Alarm);

        AlarmNumberVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlarmNumberVerifyActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Send Alarm");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        AlarmWindow.setText("Create Alarm");
        AlarmWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlarmWindowActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Make Call");

        jLabel5.setText("Alarm Number:");

        jLabel6.setText("Description:");

        jLabel7.setText("Caller Name:");

        jLabel22.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel22.setText("Alarm");

        jButton5.setText("Refresh Gui");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MakeCallLayout = new javax.swing.GroupLayout(MakeCall);
        MakeCall.setLayout(MakeCallLayout);
        MakeCallLayout.setHorizontalGroup(
            MakeCallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeCallLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlarmNumberVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MakeCallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MakeCallLayout.createSequentialGroup()
                        .addComponent(AlarmWindow)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MakeCallLayout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(427, Short.MAX_VALUE))))
            .addGroup(MakeCallLayout.createSequentialGroup()
                .addGroup(MakeCallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MakeCallLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(MakeCallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MakeCallLayout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jLabel4))
                            .addGroup(MakeCallLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(MakeCallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MakeCallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MakeCallDescritpion, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MakeCallName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(MakeCallLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(SubmitCall))))))
                    .addGroup(MakeCallLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5)
                        .addGap(253, 253, 253)
                        .addComponent(jButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MakeCallLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MakeCallLayout.setVerticalGroup(
            MakeCallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeCallLayout.createSequentialGroup()
                .addGroup(MakeCallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MakeCallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MakeCallLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(MakeCallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AlarmNumberVerify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AlarmWindow)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MakeCallLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MakeCallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MakeCallName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MakeCallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MakeCallDescritpion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SubmitCall)
                        .addGap(5102, 5102, 5102))))
        );

        Home.addTab("Make Call", MakeCall);

        Description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionActionPerformed(evt);
            }
        });

        CallerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallerNameActionPerformed(evt);
            }
        });

        PoliceCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoliceCodeActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Caller", "Description", "Hold"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        GetCall.setText("Get Call");
        GetCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetCallActionPerformed(evt);
            }
        });

        SendReport.setText("Send Report");
        SendReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendReportActionPerformed(evt);
            }
        });

        Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationActionPerformed(evt);
            }
        });

        IncidentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncidentTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OperatorLayout = new javax.swing.GroupLayout(Operator);
        Operator.setLayout(OperatorLayout);
        OperatorLayout.setHorizontalGroup(
            OperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );
        OperatorLayout.setVerticalGroup(
            OperatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Addop.setText("Add Operator");
        Addop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddopActionPerformed(evt);
            }
        });

        jLabel8.setText("Incident Type:");

        jLabel9.setText("Caller ID:");

        jLabel10.setText("Caller Name:");

        jLabel11.setText("Location:");

        jLabel12.setText("Descritpion:");

        jLabel13.setText("Police Code:");

        jLabel14.setText("Priority:");

        jLabel15.setText("Call Number:");

        jButton4.setText("Refresh Gui");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Clear");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OperatorFinalPageLayout = new javax.swing.GroupLayout(OperatorFinalPage);
        OperatorFinalPage.setLayout(OperatorFinalPageLayout);
        OperatorFinalPageLayout.setHorizontalGroup(
            OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperatorFinalPageLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OperatorFinalPageLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addGroup(OperatorFinalPageLayout.createSequentialGroup()
                        .addGroup(OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(OperatorFinalPageLayout.createSequentialGroup()
                                .addGroup(OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperatorFinalPageLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CallerIDsave, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperatorFinalPageLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CallerName, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperatorFinalPageLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Location, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperatorFinalPageLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperatorFinalPageLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PoliceCode, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperatorFinalPageLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Priority, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperatorFinalPageLayout.createSequentialGroup()
                                        .addComponent(SendReport)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Addop)))
                                .addGap(20, 20, 20))
                            .addGroup(OperatorFinalPageLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IncidentType, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(Operator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(OperatorFinalPageLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(callNumberText)
                                .addGap(18, 18, 18)
                                .addComponent(GetCall))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        OperatorFinalPageLayout.setVerticalGroup(
            OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperatorFinalPageLayout.createSequentialGroup()
                .addGroup(OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(OperatorFinalPageLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GetCall)
                            .addComponent(callNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OperatorFinalPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Operator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperatorFinalPageLayout.createSequentialGroup()
                        .addGroup(OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(OperatorFinalPageLayout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OperatorFinalPageLayout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IncidentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CallerIDsave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CallerName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Location, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(10, 10, 10)
                        .addGroup(OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PoliceCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Priority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(OperatorFinalPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Addop)
                            .addComponent(SendReport))
                        .addGap(116, 116, 116)))
                .addGap(10, 10, 10))
        );

        Home.addTab("Operator", OperatorFinalPage);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Incident #", "Priority", "Type", "Location"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        ReportSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportSearchActionPerformed(evt);
            }
        });

        GetReport.setText("Get Report");
        GetReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetReportActionPerformed(evt);
            }
        });

        IncidentNameDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncidentNameDPActionPerformed(evt);
            }
        });

        StartAssigning.setText("Start Assigning Task");
        StartAssigning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartAssigningActionPerformed(evt);
            }
        });

        newDispatcher.setText("New Dispatcher");
        newDispatcher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDispatcherActionPerformed(evt);
            }
        });

        jLabel16.setText("Incident Number:");

        jLabel17.setText("Incident Name:");

        jLabel18.setText("Incident Number:");

        jLabel19.setText("Incident Location:");

        jButton3.setText("Refresh Gui");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        ClearDp.setText("Clear");
        ClearDp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearDpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DispatcherLayout = new javax.swing.GroupLayout(Dispatcher);
        Dispatcher.setLayout(DispatcherLayout);
        DispatcherLayout.setHorizontalGroup(
            DispatcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DispatcherLayout.createSequentialGroup()
                .addGroup(DispatcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DispatcherLayout.createSequentialGroup()
                        .addContainerGap(77, Short.MAX_VALUE)
                        .addGroup(DispatcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DispatcherLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(IncidentNameDP, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DispatcherLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IncidentNumberDP, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DispatcherLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DispatcherLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DispatcherLayout.createSequentialGroup()
                                .addGroup(DispatcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(StartAssigning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(newDispatcher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(76, 76, 76)))
                        .addGap(18, 18, 18))
                    .addGroup(DispatcherLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(ClearDp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(DispatcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DispatcherLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(45, 45, 45)
                        .addComponent(ReportSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GetReport))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        DispatcherLayout.setVerticalGroup(
            DispatcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DispatcherLayout.createSequentialGroup()
                .addGroup(DispatcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DispatcherLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(DispatcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GetReport)
                            .addComponent(ReportSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addGroup(DispatcherLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DispatcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(ClearDp))))
                .addGap(18, 18, 18)
                .addGroup(DispatcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DispatcherLayout.createSequentialGroup()
                        .addGroup(DispatcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IncidentNameDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(10, 10, 10)
                        .addGroup(DispatcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IncidentNumberDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DispatcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DispatcherLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addComponent(StartAssigning)
                        .addGap(22, 22, 22)
                        .addComponent(newDispatcher))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Home.addTab("Dispatcher", Dispatcher);

        Officer.setMaximumSize(new java.awt.Dimension(295, 295));
        Officer.setPreferredSize(new java.awt.Dimension(295, 295));

        jLabel1.setText("Officer Location ");

        jLabel2.setText("Officer Assignment");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Badge Number", "Name", "Status", "Type Of Officer", "Position", "Location", "CarNumber"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        SearchButton.setToolTipText("");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        SearchLocation.setText("Search");
        SearchLocation.setToolTipText("");
        SearchLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchLocationActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        FinalAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalAssignmentActionPerformed(evt);
            }
        });

        CompleteAssignment.setText("Assign");
        CompleteAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompleteAssignmentActionPerformed(evt);
            }
        });

        jButton1.setText("Add new Officer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        UpdateBadgeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBadgeStatusActionPerformed(evt);
            }
        });

        UpdateStaus.setText("Update Status");
        UpdateStaus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateStausActionPerformed(evt);
            }
        });

        jLabel20.setText("Officer Status");

        jLabel23.setText("Incident  #");

        jLabel24.setText("Officer Badge:");

        jButton2.setText("Refresh Gui");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton8.setText("Clear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OfficerLayout = new javax.swing.GroupLayout(Officer);
        Officer.setLayout(OfficerLayout);
        OfficerLayout.setHorizontalGroup(
            OfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OfficerLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(OfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OfficerLayout.createSequentialGroup()
                        .addGroup(OfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel20)
                            .addComponent(jLabel24))
                        .addGap(32, 32, 32)
                        .addGroup(OfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UpdateBadgeStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(EditStatus)
                            .addComponent(SearchButton)))
                    .addComponent(FinalAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(OfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OfficerLayout.createSequentialGroup()
                        .addComponent(SearchLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UpdateStaus, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(OfficerLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(FinalIncidentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CompleteAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OfficerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OfficerLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 449, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        OfficerLayout.setVerticalGroup(
            OfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OfficerLayout.createSequentialGroup()
                .addGroup(OfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OfficerLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1))
                    .addGroup(OfficerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(OfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton8))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(OfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(OfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SearchLocation)
                        .addComponent(Reset)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBadgeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(11, 11, 11)
                .addGroup(OfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(UpdateStaus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OfficerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FinalAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(FinalIncidentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CompleteAssignment))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Home.addTab("Officer Info", Officer);

        AssigmentStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Assignment Number", "Officer Name", "Badge", "Incident Report", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(AssigmentStatusTable);

        CompleteUpdate.setText("Complete");
        CompleteUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompleteUpdateActionPerformed(evt);
            }
        });

        jLabel3.setText("Assignment Name:");

        jLabel21.setText("Incident Number:");

        Refresh.setText("Refresh Gui");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        jButton9.setText("Clear");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CompleteLayout = new javax.swing.GroupLayout(Complete);
        Complete.setLayout(CompleteLayout);
        CompleteLayout.setHorizontalGroup(
            CompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CompleteLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(CompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CompleteLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(CompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(CompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AssignmentPK, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(CompleteUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Verify))))
                .addGap(91, 91, 91))
            .addGroup(CompleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Refresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap())
        );
        CompleteLayout.setVerticalGroup(
            CompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompleteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Refresh)
                    .addComponent(jButton9))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(CompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AssignmentPK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(CompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(Verify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CompleteUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Home.addTab("Complete", Complete);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Home, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 584, Short.MAX_VALUE))
        );

        Home.getAccessibleContext().setAccessibleName("OfficerInfo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationActionPerformed

    private void CallerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CallerNameActionPerformed

    private void DescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionActionPerformed

    private void GetCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetCallActionPerformed
        int id = Integer.parseInt(callNumberText.getText().trim());
        UpdateSQL.CallStatus(id);
        SQLConnections.callerInformaiton();
         CallerTable();
        GetCall(id);
        
    }//GEN-LAST:event_GetCallActionPerformed

    private void MakeCallNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeCallNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MakeCallNameActionPerformed

    private void SearchLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchLocationActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.getDataVector().removeAllElements();
        for (int i = 0; i < SQLConnections.officersList.size(); i++) {
            if (SearchButton.getText().equals(SQLConnections.officersList.get(i).getLocation())) {
                String name = SQLConnections.officersList.get(i).getName();
                String status = SQLConnections.officersList.get(i).getStatus();
                String officerType = SQLConnections.officersList.get(i).getOfficerType();
                String position = SQLConnections.officersList.get(i).getPosition();
                String location = SQLConnections.officersList.get(i).getLocation();
                int badgeNumber = SQLConnections.officersList.get(i).getBadgeNumber();
                int carNumber = SQLConnections.officersList.get(i).getCarNumber();
                Object[] tablerow = {Integer.toString(badgeNumber), name, status, officerType,
                    position, location,
                    Integer.toString(carNumber)};
                model.addRow(tablerow);
            }
        }
    }//GEN-LAST:event_SearchLocationActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        for (int i = 0; i < SQLConnections.officersList.size(); i++) {
            if (SearchButton.getText().equals(SQLConnections.officersList.get(i).getLocation())) {
                String name = SQLConnections.officersList.get(i).getName();
                String status = SQLConnections.officersList.get(i).getStatus();
                String officerType = SQLConnections.officersList.get(i).getOfficerType();
                String position = SQLConnections.officersList.get(i).getPosition();
                String location = SQLConnections.officersList.get(i).getLocation();
                int badgeNumber = SQLConnections.officersList.get(i).getBadgeNumber();
                int carNumber = SQLConnections.officersList.get(i).getCarNumber();
                Object[] tablerow = {Integer.toString(badgeNumber), name, status, officerType,
                    position, location,
                    Integer.toString(carNumber)};
                model.addRow(tablerow);
            }
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void GetCall(int id) {
        try {
            for (int i = 0; i < SQLConnections.callerList.size(); i++) {
                if (SQLConnections.callerList.get(i).getCallerID() == id) {
                    //   System.out.println(SQLConnections.callerList.get(i).getCallerID());
                    //   JOptionPane.showMessageDialog(null, "Caller Name : "+SQLConnections.callerList.get(i).getName()+ "\n"
                    //   +"Description: \n"+SQLConnections.callerList.get(i).getDescription());
                    JFrame frame = new JFrame("Test Frame");
                    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    JLabel label = new JLabel("My label", SwingConstants.CENTER);
                    label.setText("Caller Name : " + SQLConnections.callerList.get(i).getName() + "\n"
                            + "Description: \n" + SQLConnections.callerList.get(i).getDescription());

                    frame.add(label);
                    frame.setSize(new Dimension(500, 200));

                    frame.setVisible(true);

                }
            }
        } catch (Exception e) {
            System.out.println("Does not exist");
        }

    }

    private void GetReportInfo(int i) {
        JFrame frame = new JFrame("Test Frame");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        JLabel label = new JLabel("My label");
        label.setText("Caller Name : " + SQLConnections.incidentList.get(i).getName() + "\n"
                + "Description: \n" + SQLConnections.incidentList.get(i).getDescription());
        label.setLocation(100, 50);
        JLabel label2 = new JLabel("My label");
        label2.setText("Caller Name : " + SQLConnections.incidentList.get(i).getName() + "\n"
                + "Description: \n" + SQLConnections.incidentList.get(i).getDescription());
        label2.setLocation(10, 60);
        JPanel p = new JPanel();
        frame.add(label);
        frame.add(label2);
        //p.setSize(new Dimension( 500, 200 ));
        // frame.add(p);
        //frame.add(label);
        //frame.add(label2);
        frame.setSize(new Dimension(500, 200));

        frame.setVisible(true);
    }


    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        OfficerTable();
    }//GEN-LAST:event_ResetActionPerformed

    private void SubmitCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitCallActionPerformed
        String name = MakeCallName.getText();
        String description = MakeCallDescritpion.getText();
        InsertSQL.InsertCall(name, description);
        SQLConnections.callerInformaiton();
        CallerTable();
        SQLConnections.IncidentReportInfo();
        updateIncidentReport();
    }//GEN-LAST:event_SubmitCallActionPerformed

    private void SendReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendReportActionPerformed
        String callid = CallerIDsave.getText().trim();
        String name = CallerName.getText();
        String description = Description.getText();
        String location = Location.getText();
        String incidentType = IncidentType.getText();
        String priority = Priority.getText();
        String policeCode = PoliceCode.getText();
        System.out.print(incidentType + " " + name + " " + location + " "
                + description + " " + Integer.parseInt(policeCode.trim()));
        InsertSQL.IncidentReport(incidentType, name, location,
                description, Integer.parseInt(policeCode));
        InsertSQL.Priority(priority, InsertSQL.getIncidentReportPK());
        InsertSQL.ReicieveCallIncidentReport(Integer.parseInt(callid), InsertSQL.getIncidentReportPK());
        System.out.println("done");
    }//GEN-LAST:event_SendReportActionPerformed

    private void PoliceCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoliceCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PoliceCodeActionPerformed

    private void IncidentNameDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncidentNameDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IncidentNameDPActionPerformed

    private void ReportSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportSearchActionPerformed

    private void GetReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetReportActionPerformed
        String number = ReportSearch.getText().trim();

        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        // model.getDataVector().removeAllElements();
        model.setRowCount(0);

        for (int i = 0; i < SQLConnections.incidentList.size(); i++) {
            //String name = SQLConnections.users.get(i).getName();
            int incidentNumber = SQLConnections.incidentList.get(i).getIncidentReport();
            if (Integer.parseInt(number) == incidentNumber) {
                GetReportInfo(i);
                int priority = SQLConnections.incidentList.get(i).getPriorityType();
                String type = SQLConnections.incidentList.get(i).getIncidentType();
                String Location = SQLConnections.incidentList.get(i).getLocation();

                Object[] Arow = {Integer.toString(incidentNumber), Integer.toString(priority), type, Location};
                model.addRow(Arow);
            }
        }
    }//GEN-LAST:event_GetReportActionPerformed

    private void StartAssigningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartAssigningActionPerformed
        String name = IncidentNameDP.getText();
        String Number = IncidentNumberDP.getText();
        String Location = DispatcherLocation.getText();
        FinalAssignment.setText(name);
        FinalIncidentNumber.setText(Number);
        SearchButton.setText(Location);
    }//GEN-LAST:event_StartAssigningActionPerformed

    private void CompleteAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteAssignmentActionPerformed
        int incidentNumber = Integer.parseInt(FinalIncidentNumber.getText().trim());
        int responder = Integer.parseInt(UpdateBadgeStatus.getText().trim());
        String Assignment = FinalAssignment.getText();
        InsertSQL.ResponderAssignment(responder, Assignment, incidentNumber);
        System.out.println("Complete");
        SQLConnections.OfficerAssigments();
        OfficerAssignmentTableUpdate();

    }//GEN-LAST:event_CompleteAssignmentActionPerformed

    private void CompleteUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompleteUpdateActionPerformed

        String assignment = AssignmentPK.getText().trim();
        int incidentkey = Integer.parseInt(Verify.getText().trim());
        for (int i = 0; i < SQLConnections.officerAssignmentList.size(); i++) {
            if (assignment.contains(SQLConnections.officerAssignmentList.get(i).getAssignment())
                    && incidentkey == SQLConnections.officerAssignmentList.get(i).getIncidentReportID()) {
                int key = SQLConnections.officerAssignmentList.get(i).getAssignmentNumber();
                UpdateSQL.ResponderAssignment(key);
            }
        }


    }//GEN-LAST:event_CompleteUpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();

        AddNewOfficer hc = new AddNewOfficer();
        hc.setVisible(true);
          }//GEN-LAST:event_jButton1ActionPerformed

    private void UpdateStausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateStausActionPerformed
        String updateStatus = EditStatus.getText();
        int badge = Integer.parseInt(UpdateBadgeStatus.getText().trim());
        UpdateSQL.ResponderStatus(badge, updateStatus);
        SQLConnections.OfficerInformation();
        OfficerTable();

    }//GEN-LAST:event_UpdateStausActionPerformed

    private void UpdateBadgeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBadgeStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateBadgeStatusActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        int AlarmNumber = Integer.parseInt(AlarmNumberVerify.getText().trim());
        for (int i = 0; i < SQLConnections.alarmList.size(); i++) {
            if (SQLConnections.alarmList.get(i).getAlarmID() == AlarmNumber) {
                String callid = Integer.toString(AlarmNumber);
                String name = SQLConnections.alarmList.get(i).getAlarmName();
                String description = "Sent from an Alarm ";
                String location = SQLConnections.alarmList.get(i).getAlarmLocation();
                String incidentType = SQLConnections.alarmList.get(i).getAlarmType();
                String priority = "2";
                String policeCode = "3";
                System.out.print(incidentType + " " + name + " " + location + " "
                        + description + " " + Integer.parseInt(policeCode.trim()));
                InsertSQL.IncidentReport(incidentType, name, location,
                        description, Integer.parseInt(policeCode));
                InsertSQL.Priority(priority, InsertSQL.getIncidentReportPK());
                InsertSQL.ReicieveCallIncidentReport(Integer.parseInt(callid), InsertSQL.getIncidentReportPK());
            }

        }
        SQLConnections.IncidentReportInfo();
        updateIncidentReport();

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void AddopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddopActionPerformed
        dispose();

        AddOperator hc = new AddOperator();
        hc.setVisible(true);
    }//GEN-LAST:event_AddopActionPerformed

    private void newDispatcherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDispatcherActionPerformed
        dispose();

        CreateNewDispatcher hc = new CreateNewDispatcher();
        hc.setVisible(true);
    }//GEN-LAST:event_newDispatcherActionPerformed

    private void AlarmWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlarmWindowActionPerformed
        dispose();

        CreateAlarm hc = new CreateAlarm();
        hc.setVisible(true);
    }//GEN-LAST:event_AlarmWindowActionPerformed

    private void AlarmNumberVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlarmNumberVerifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlarmNumberVerifyActionPerformed

    private void IncidentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncidentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IncidentTypeActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        Refresh();
    }//GEN-LAST:event_RefreshActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Refresh();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Refresh();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Refresh();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Refresh();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ClearDpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearDpActionPerformed
       ReportSearch.setText("");
       IncidentNameDP.setText("");
       IncidentNumberDP.setText("");
       DispatcherLocation.setText("");
    }//GEN-LAST:event_ClearDpActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        AlarmNumberVerify.setText("");
        MakeCallName.setText("");
        MakeCallDescritpion.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        SearchButton.setText("");
        UpdateBadgeStatus.setText("");
          FinalAssignment.setText("");
        FinalIncidentNumber.setText("");
        EditStatus.setText("");
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
AssignmentPK.setText("");
Verify.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         CallerIDsave.setText("");
      CallerName.setText("");
        Description.setText("");
         Location.setText("");
         IncidentType.setText("");
        Priority.setText("");
         PoliceCode.setText("");
         callNumberText.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void FinalAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalAssignmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalAssignmentActionPerformed

    private void Insert() {

    }

    private void SendReport() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoliceDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoliceDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoliceDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoliceDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoliceDB().setVisible(true);
            }
        });
    }

    public void OfficerAssignmentTableUpdate() {
        DefaultTableModel model = (DefaultTableModel) AssigmentStatusTable.getModel();
        model.setRowCount(0);
        for (int i = 0; i < SQLConnections.officerAssignmentList.size(); i++) {
            String Done = "No";

            String name = SQLConnections.officerAssignmentList.get(i).getName();
            String ASSIGNMET = SQLConnections.officerAssignmentList.get(i).getAssignment();
            int number = SQLConnections.officerAssignmentList.get(i).getAssignmentNumber();
            int badge = SQLConnections.officerAssignmentList.get(i).getBadgeNumber();
            boolean Complete = SQLConnections.officerAssignmentList.get(i).getComplete();
            int incidentNumber = SQLConnections.officerAssignmentList.get(i).getIncidentReportID();

            if (Complete) {
                Done = "Yes";
            }
            Object[] tablerow = {ASSIGNMET, name, Integer.toString(badge), Integer.toString(incidentNumber),
                Done};
            model.addRow(tablerow);
        }
    }

    public void OfficerTable() {

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        for (int i = 0; i < SQLConnections.officersList.size(); i++) {
            String name = SQLConnections.officersList.get(i).getName();
            String status = SQLConnections.officersList.get(i).getStatus();
            String officerType = SQLConnections.officersList.get(i).getOfficerType();
            String position = SQLConnections.officersList.get(i).getPosition();
            String location = SQLConnections.officersList.get(i).getLocation();
            int badgeNumber = SQLConnections.officersList.get(i).getBadgeNumber();
            int carNumber = SQLConnections.officersList.get(i).getCarNumber();
            Object[] tablerow = {Integer.toString(badgeNumber), name, status, officerType,
                position, location,
                Integer.toString(carNumber)};
            model.addRow(tablerow);

        }
    }

    public void updateIncidentReport() {
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        // model.getDataVector().removeAllElements();
        model.setRowCount(0);

        for (int i = 0; i < SQLConnections.incidentList.size(); i++) {
            //String name = SQLConnections.users.get(i).getName();
            int incidentNumber = SQLConnections.incidentList.get(i).getIncidentReport();
            int priority = SQLConnections.incidentList.get(i).getPriorityType();
            String type = SQLConnections.incidentList.get(i).getIncidentType();
            String Location = SQLConnections.incidentList.get(i).getLocation();

            Object[] Arow = {Integer.toString(incidentNumber), Integer.toString(priority), type, Location};
            model.addRow(Arow);
        }
    }

    public void AlarmTableGrid() {
        DefaultTableModel model = (DefaultTableModel) Alarm.getModel();
        // model.getDataVector().removeAllElements();
        model.setRowCount(0);
        for (int i = 0; i < SQLConnections.alarmList.size(); i++) {
            int id = SQLConnections.alarmList.get(i).getAlarmID();
            String name = SQLConnections.alarmList.get(i).getAlarmName();
            String location = SQLConnections.alarmList.get(i).getAlarmLocation();
            String type = SQLConnections.alarmList.get(i).getAlarmType();
            Object[] row = {id, name, type, location};
            model.addRow(row);
        }
    }

    public void CallerTable() {
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        // model.getDataVector().removeAllElements();
        model.setRowCount(0);

        for (int i = 0; i < SQLConnections.callerList.size(); i++) {
            String hold = "hold";
            //String name = SQLConnections.users.get(i).getName();
            String name = SQLConnections.callerList.get(i).getName();
            String status = SQLConnections.callerList.get(i).getDescription();

            if (SQLConnections.callerList.get(i).isHoldStatus()) {
                hold = "active";
            }
            int callerId = SQLConnections.callerList.get(i).getCallerID();

            Object[] row = {callerId, status, hold};
            model.addRow(row);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addop;
    private javax.swing.JTable Alarm;
    private javax.swing.JTextField AlarmNumberVerify;
    private javax.swing.JButton AlarmWindow;
    private javax.swing.JTable AssigmentStatusTable;
    private javax.swing.JTextField AssignmentPK;
    private javax.swing.JTextField CallerIDsave;
    private javax.swing.JTextField CallerName;
    private javax.swing.JButton ClearDp;
    private javax.swing.JPanel Complete;
    private javax.swing.JButton CompleteAssignment;
    private javax.swing.JButton CompleteUpdate;
    private javax.swing.JTextField Description;
    private javax.swing.JPanel Dispatcher;
    private javax.swing.JTextField DispatcherLocation;
    private javax.swing.JTextField EditStatus;
    private javax.swing.JTextField FinalAssignment;
    private javax.swing.JTextField FinalIncidentNumber;
    private javax.swing.JButton GetCall;
    private javax.swing.JButton GetReport;
    private javax.swing.JTabbedPane Home;
    private javax.swing.JTextField IncidentNameDP;
    private javax.swing.JTextField IncidentNumberDP;
    private javax.swing.JTextField IncidentType;
    private javax.swing.JTextField Location;
    private javax.swing.JPanel MakeCall;
    private javax.swing.JTextField MakeCallDescritpion;
    private javax.swing.JTextField MakeCallName;
    private javax.swing.JPanel Officer;
    private javax.swing.JPanel Operator;
    private javax.swing.JPanel OperatorFinalPage;
    private javax.swing.JTextField PoliceCode;
    private javax.swing.JTextField Priority;
    private javax.swing.JButton Refresh;
    private javax.swing.JTextField ReportSearch;
    private javax.swing.JButton Reset;
    private javax.swing.JTextField SearchButton;
    private javax.swing.JButton SearchLocation;
    private javax.swing.JButton SendReport;
    private javax.swing.JButton StartAssigning;
    private javax.swing.JToggleButton SubmitCall;
    private javax.swing.JTextField UpdateBadgeStatus;
    private javax.swing.JButton UpdateStaus;
    private javax.swing.JTextField Verify;
    private javax.swing.JTextField callNumberText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton newDispatcher;
    // End of variables declaration//GEN-END:variables
}
